version: "2.1"

volumes:
  ms-conf:
    driver_opts:
      type: none
      device: /opt/metersphere/conf
      o: bind
  ms-logs:
    driver_opts:
      type: none
      device: /opt/metersphere/logs
      o: bind
  ms-data:
    driver_opts:
      type: none
      device: /opt/metersphere/data
      o: bind

networks:
  ms-network:
    external: true
services:
  eureka:
    image: e2fc6cd97a17
    container_name: eureka210
#    ports:
#      - '8761:8761' # 默认不开启
    environment:
      REDIS_HOST: MS-Redis
      REDIS_PORT: 6379
      REDIS_PASSWORD:
    healthcheck:
      test: [ "CMD", "nc", "-zv", "localhost", "8761" ]
      interval: 6s
      timeout: 10s
      retries: 50
    restart: always
    volumes:
      - ms-conf:/opt/metersphere/conf
      - ms-logs:/opt/metersphere/logs
      - ms-data:/opt/metersphere/data
    mem_limit: ${MS_EUREKA_MEM_LIMIT:-536870912} # default 512m bytes
    networks:
      - ms-network
